### PR TITLE
Add armv5 support

### PR DESCRIPTION
**Pull request by hberntsen**
This adds support for armv5 targets :smiley:

### CODE REVIEW

**Comment by otavio** [comment]
I am wondering if you need to run it against all previous releases as it might fail to run if we choose any of the old ones.

**Comment by otavio** [comment]
Please refer to #86 about which releases I am proposing to maintain.

**Comment by hberntsen** [comment]
Good point. I added it to older releases! Versions prior 1.35 gave a license error so I couldn't update them. The error:
```
ERROR: Apache license file hash has changed for cargo-0.32.0-aarch64-unknown-linux-gnu.tar.gz
  Actual: 1836efb2eb779966696f473ee8540542
  Expected: 71b224ca933f0676e26d5c2e2271331c
```

I see that the hash in the download script changed at some point so I guess this is nothing new.

**Comment by posborne** [comment]
Thanks @hberntsen; can you rebase and fixup the conflicts (drop changes to versions that are now removed).  Will also want to add for 1.46.0.  Thanks!  Other LGTM.

**Comment by hberntsen** [comment]
Done!

**Comment by posborne** [comment]
Thanks @hberntsen

**Review by posborne — APPROVED** [review]

**Pull request merged**
