### PR TITLE
Add Rust 1.30.0

### PR DESCRIPTION
**Pull request by iohe**
Be gentle, still lerning how to do PR.
Add 1.30.0 support

### CODE REVIEW

**Comment by nastevens** [comment]
Build is currently broken - looks like the `COPYRIGHT` file upstream changed and our existing implementation is pretty naive: https://github.com/rust-embedded/meta-rust-bin/blob/master/build-new-version.sh#L180. Do you want to try and tackle the changes needed to the script to dynamically write the copyright MD5?

**Comment by iohe** [comment]
autocompute md5 for COPYRIGHT file, updated file for rustc and verified that it works.

**Comment by nastevens** [comment]
I just found out that Rust 1.30.1 is [planned to be released today](https://github.com/rust-lang/rust/issues/55594) so we'd be bumping almost immediately. Do you have any objections to waiting for 1.30.1 and then using that?

**Comment by iohe** [comment]
Fine with me. As a newbie with github/git and PR, please let me know recommended steps (other than running the script with 1.30.1

**Comment by posborne** [comment]
> Fine with me. As a newbie with github/git and PR, please let me know recommended steps (other than running the script with 1.30.1

If you have a project using the layer, that would be the other validation to perform.  We don't currently have CI setup to automate that as part of this project so @nastevens and I can do that testing as well prior to merge.

**Comment by fredszaq** [comment]
Hi there!
I've got a fairly big rust project that needs rust 1.30 to compile and it compiled without any problems on an aarch64 target using this branch.
This looks ready to be merged

**Comment by posborne** [comment]
@fredszaq Thanks for testing and thanks @iohe for the contribution.  Merging.

**Pull request merged**
