### PR TITLE
Fix #11

### LINKED ISSUE #11: upgrade to rust 1.14
Any plans ? :)

### PR DESCRIPTION
**Pull request by egimbernat**
Hey folks, I just noticed that the layer doesn't load correctly the classes on Honister and that made the layer to brake the parsing. I made simple formatting modifications based on Poky ones.

### CODE REVIEW

**Comment by hellow554** [comment]
Can you edit your text of this PR and add `Fix #11`?

For more information see https://docs.github.com/en/enterprise-server@3.0/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Comment by egimbernat** [comment]
Sure

**Comment by neithanmo** [comment]
Hi @egimbernat thanks for this. Unfortunately, after applying this fix locally, I got a similar error later during the build process:
```
WARNING: /home/shared/my-distro/poky/meta/recipes-devtools/rust/rust-cross-canadian_1.54.0.bb: Exception during build_dependencies for TARGET_LLVM_FEATURES
WARNING: /home/shared/my-distro/poky/meta/recipes-devtools/rust/rust-cross-canadian_1.54.0.bb: Error during finalise of /home/shared/my-distro/poky/me
ta/recipes-devtools/rust/rust-cross-canadian_1.54.0.bb
ERROR: ExpansionError during parsing /home/shared/my-distro/poky/meta/recipes-devtools/rust/rust-cross-canadian_1.54.0.bb
Traceback (most recent call last):
  File "Var <TARGET_LLVM_FEATURES>", line 1, in <module>                               
  File "/home/shared/my-distro/poky/meta/recipes-devtools/rust/rust-common.inc", line 117, in llvm_features(d=<bb.data_smart.DataSmart object at 0x7feb4753c9e8>):
         return ','.join(llvm_features_from_tune(d) +                                  
    >                    llvm_features_from_cc_arch(d) +                               
                         llvm_features_from_target_fpu(d))                             
  File "/home/shared/my-distro/poky/meta/recipes-devtools/rust/rust-common.inc", line 36, in llvm_features_from_tune(d=<bb.data_smart.DataSmart object at 0x7feb47
53c9e8>):                                  
                                           
    >    if target_is_armv7(d):
             f.append('+v7')
bb.data_smart.ExpansionError: Failure expanding variable TARGET_LLVM_FEATURES, expression was ${@llvm_features(d)} which triggered exception NameError: name 'target_is_armv7'
 is not defined                            
The variable dependency chain for the failure is: TARGET_LLVM_FEATURES
```
I am using Honister, and actually, I am trying to replace __meta-rust__, with __meta-rust-bin__. The first one works smoothly with Honister but we need rust 1.56.0.
another completely different thing is that meta-rust-bin tries to pull rust 1.54.0, although I specified rust 1.56.0 using what is described [here](https://github.com/rust-embedded/meta-rust-bin/issues/89). 

Looking forward to this being merged.

**Comment by hellow554** [comment]
> I am using Honister, and actually, I am trying to replace **meta-rust**, with **meta-rust-bin**.

It you are on honister there is no need to use any of those layers anymore, because rust has been integrated  into poky itself: https://git.yoctoproject.org/poky/tree/meta/recipes-devtools/rust

Effectively that is the meta-rust layer.

**Comment by 8joshua88** [comment]
I can confirm that this is the fix for the issue that @egimbernat and I am having. 

I also have a PR that I am putting together that includes  Fix#11 and two minor variable changes that makes this layer kirkstone compatible.


> Hi @egimbernat thanks for this. Unfortunately, after applying this fix locally, I got a similar error later during the build process:
> 
> ```
> WARNING: /home/shared/my-distro/poky/meta/recipes-devtools/rust/rust-cross-canadian_1.54.0.bb: Exception during build_dependencies for TARGET_LLVM_FEATURES
> WARNING: /home/shared/my-distro/poky/meta/recipes-devtools/rust/rust-cross-canadian_1.54.0.bb: Error during finalise of /home/shared/my-distro/poky/me
> ta/recipes-devtools/rust/rust-cross-canadian_1.54.0.bb
> ERROR: ExpansionError during parsing /home/shared/my-distro/poky/meta/recipes-devtools/rust/rust-cross-canadian_1.54.0.bb
> Traceback (most recent call last):
>   File "Var <TARGET_LLVM_FEATURES>", line 1, in <module>                               
>   File "/home/shared/my-distro/poky/meta/recipes-devtools/rust/rust-common.inc", line 117, in llvm_features(d=<bb.data_smart.DataSmart object at 0x7feb4753c9e8>):
>          return ','.join(llvm_features_from_tune(d) +                                  
>     >                    llvm_features_from_cc_arch(d) +                               
>                          llvm_features_from_target_fpu(d))                             
>   File "/home/shared/my-distro/poky/meta/recipes-devtools/rust/rust-common.inc", line 36, in llvm_features_from_tune(d=<bb.data_smart.DataSmart object at 0x7feb47
> 53c9e8>):                                  
>                                            
>     >    if target_is_armv7(d):
>              f.append('+v7')
> bb.data_smart.ExpansionError: Failure expanding variable TARGET_LLVM_FEATURES, expression was ${@llvm_features(d)} which triggered exception NameError: name 'target_is_armv7'
>  is not defined                            
> The variable dependency chain for the failure is: TARGET_LLVM_FEATURES
> ```
> 
> I am using Honister, and actually, I am trying to replace **meta-rust**, with **meta-rust-bin**. The first one works smoothly with Honister but we need rust 1.56.0. another completely different thing is that meta-rust-bin tries to pull rust 1.54.0, although I specified rust 1.56.0 using what is described [here](https://github.com/rust-embedded/meta-rust-bin/issues/89).
> 
> Looking forward to this being merged.


@neithanmo, to what @hellow554 mentioned, rust has become part of poky. Depending on your yocto version, you may need to add this to your bblayers.conf:
```
BBMASK += " \
 ./meta/recipes-devtools/rust \
 ./OEROOT##/meta/recipes-devtools/cargo \
  "
 ```

**Comment by posborne** [comment]
Superseded by #123 which includes these changes, thanks @egimbernat

**Pull request closed without merging**
